### ISSUE TITLE
Local development Bucket "Get Url" returns "http://supabase_kong_MyApp:8000/storage/v1/..."

### ISSUE THREAD

**Issue by socramm9** [supabase/cli#1079]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

When getting the public Url for a file in a Bucket it should return a localhost url but instead it returns:
**_http://supabase_kong_MyApp:8000_**/storage/v1/object/public/avatars/53fc14c1-fe01-4210-b33c-291bd27af451/avatar.png

This happens in the [Dashboard UI](http://localhost:54323/project/default/storage/buckets)  as also using an edge function.

Because of that I can't use the URL in my Frontend

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Upload File to a bucket
2. Select File
3. Click "Get Url"

## Expected behavior

Instead of `supabase_kong_MyApp:8000` a localhost address should be returned to be used locally.

**Comment by socramm9** [comment]
I updated to 1.57.3 but issue still persists

**Comment by sweatybridge** [comment]
We have merged a couple more fixes https://github.com/supabase/supabase/pull/14252. I will make another release address this.

**Comment by socramm9** [comment]
Do I have to do an extra Step to update Supabase? I installed the new version an run `supabase stop` and `supabase start` but the issue still persists.


https://github.com/supabase/cli/assets/52098754/1cde9ed9-691e-48cb-ace6-1cefa30ed13d

**Comment by sweatybridge** [comment]
After supabase start, could you show me the output of `docker ps -a`? Just want to make sure the studio image version is correct

**Comment by socramm9** [comment]
Sure 
<img width="1604" alt="Bildschirmfoto 2023-05-12 um 00 36 47" src="https://github.com/supabase/cli/assets/52098754/0a801ade-42af-41ee-944d-f4cf93f935a2">

**Comment by sweatybridge** [comment]
Thanks, I can reproduce this on `public` buckets.

**Comment by socramm9** [comment]
@sweatybridge Thanks for the fix it works now on the Dashboard, but it does not work from code

```
import { createClient } from "https://esm.sh/@supabase/supabase-js@2.21.0";

const { publicUrl } = supabase.storage
      .from("avatars")
      .getPublicUrl(filePath).data;
```

**Comment by sweatybridge** [comment]
Hmm this is a bit tricky because the edge function code runs inside a container but the url that storage returns need to work outside. I think a temporary workaround is to replace the [host and protocol](https://github.com/supabase/supabase/blob/master/studio/pages/api/storage/%5Bref%5D/buckets/%5Bid%5D/objects/public-url.ts#L27) manually in your code, like the linked example.

@inian do you see other alternatives? like adding a `SUPABASE_PUBLIC_URL` to supabase-js?

**Comment by socramm9** [comment]
Hmmm tricky. It would be nice to have an out of the box solution whiteout a workaround. But if that it is what is has to be I will write a function to handle it like that. 

Please keep me updated 😊

**Comment by bombillazo** [comment]
How about if in the storage client, the download link functions check if the URL contains the internal edge function SUPABASE_URL (the kong url) used by the edge function and if it is, rewrite it to the localhost:54321 endpoint?

**Comment by besteman** [comment]
> Hmm this is a bit tricky because the edge function code runs inside a container but the url that storage returns need to work outside. I think a temporary workaround is to replace the [host and protocol](https://github.com/supabase/supabase/blob/master/studio/pages/api/storage/%5Bref%5D/buckets/%5Bid%5D/objects/public-url.ts#L27) manually in your code, like the linked example.
> 
> @inian do you see other alternatives? like adding a `SUPABASE_PUBLIC_URL` to supabase-js?

@sweatybridge what is the work around here? the link is broken. Also is there an update on this?

**Comment by marchrius** [comment]
Just found this from an issue on (archived) supabase-js repository. Which workaround are we talking about? The link in https://github.com/supabase/cli/issues/1079#issuecomment-1546058111 is broken.
