### ISSUE TITLE
DB Reset breaking database

### ISSUE THREAD

**Issue by oliviercperrier** [supabase/cli#123]
# Bug report

## Describe the bug

When i run db reset with or without migrations script, i get the following error when trying to signn up new user: `Database error finding user`

## To Reproduce

1. supabase init
2. supabase start
3. supabase db reset
4. Try signup a new user
5. see error 500

## Expected behavior

Db reset should not break database 

## System information

- OS: macOs
- version supabase cli: 0.15.10

**Comment by soedirgo** [comment]
Thanks for noticing this - should be fixed in v0.15.11. Can you update the CLI and see if it works?

**Comment by oliviercperrier** [comment]
@soedirgo Hi, i just upgraded supabase cli to 0.15.13, but i still get the same problem.

**Comment by oliviercperrier** [comment]
@soedirgo Thanks. I just upgraded supabase to 0.15.13 ans it seems to be working. Closing this bug.
