### ISSUE TITLE
`daemon: invalid reference format` error

### ISSUE THREAD

**Issue by bombillazo** [supabase/cli#1676]
**Describe the bug**

Whe running the Supabase stack locally on v1.115.0, we get a docker error:

```sh
 supabase start --debug
Supabase CLI 1.115.0
2023/11/20 10:40:48 Sent Header: Host [api.moby.localhost]
2023/11/20 10:40:48 Sent Header: User-Agent [Docker-Client/unknown-version (darwin)]
2023/11/20 10:40:48 Send Done
2023/11/20 10:40:48 Recv First Byte
2023/11/20 10:40:48 Sent Header: Host [api.moby.localhost]
2023/11/20 10:40:48 Sent Header: User-Agent [Docker-Client/unknown-version (darwin)]
2023/11/20 10:40:48 Send Done
2023/11/20 10:40:48 Recv First Byte
2023/11/20 10:40:48 Sent Header: Host [api.moby.localhost]
2023/11/20 10:40:48 Sent Header: User-Agent [Docker-Client/unknown-version (darwin)]
2023/11/20 10:40:48 Send Done
2023/11/20 10:40:48 Recv First Byte
2023/11/20 10:40:48 Sent Header: Host [api.moby.localhost]
2023/11/20 10:40:48 Sent Header: User-Agent [Docker-Client/unknown-version (darwin)]
2023/11/20 10:40:48 Send Done
2023/11/20 10:40:48 Recv First Byte
Error response from daemon: invalid reference format
```

**To Reproduce**
1. Run `supabase start`
 
**Expected behavior**

**Desktop (please complete the following information):**
 - Version of supabase-cli 1.115.0

**Comment by sweatybridge** [comment]
Sorry about that. It was missing a template string substitution. Should be fixed in beta release now.

**Comment by dkjonzy2** [comment]
I am still getting this issue. Using supabase cli version 1.123.3

**Comment by sweatybridge** [comment]
@dkjonzy2 Could you remove `supabase/.temp` and try again?

If that doesn't help, could you share your `supabase/config.toml` here?

**Comment by dkjonzy2** [comment]
Deleteing the `supabase/.temp` file solved the issue. Thanks!
