### ISSUE TITLE
PostgREST 12.1 frequently stuck in "Attempting to connect to the database..." (Local Development)

### ISSUE THREAD

**Issue by vhpx** [supabase/cli#2361]
**Describe the bug**

Supabase PostgREST docker container logs:

```bash
2024-06-03 16:12:18 03/Jun/2024:09:12:18 +0000: Starting PostgREST 12.1...
2024-06-03 16:12:18 03/Jun/2024:09:12:18 +0000: Attempting to connect to the database...
2024-06-03 16:12:18 03/Jun/2024:09:12:18 +0000: Admin server listening on port 3001
2024-06-03 16:12:18 03/Jun/2024:09:12:18 +0000: Listening on port 3000
2024-06-03 16:12:18 03/Jun/2024:09:12:18 +0000: Listening for notifications on the "pgrst" channel
2024-06-03 16:12:18 03/Jun/2024:09:12:18 +0000: Successfully connected to PostgreSQL 15.1 (Ubuntu 15.1-1.pgdg20.04+1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0, 64-bit
2024-06-03 16:12:18 03/Jun/2024:09:12:18 +0000: Config reloaded
2024-06-03 16:12:19 03/Jun/2024:09:12:18 +0000: Schema cache queried in 7.2 milliseconds
2024-06-03 16:12:19 03/Jun/2024:09:12:18 +0000: Schema cache loaded 87 Relations, 83 Relationships, 48 Functions, 0 Domain Representations, 4 Media Type Handlers
2024-06-03 16:17:57 03/Jun/2024:09:17:57 +0000: Starting PostgREST 12.1...
2024-06-03 16:17:57 03/Jun/2024:09:17:57 +0000: Attempting to connect to the database...
2024-06-03 16:17:57 03/Jun/2024:09:17:57 +0000: Admin server listening on port 3001
2024-06-03 16:17:57 03/Jun/2024:09:17:57 +0000: Listening on port 3000
2024-06-03 16:17:57 Assertion failed: *(&once->n) != 4 (threads.c: k5_once: 564)
2024-06-03 16:17:57 03/Jun/2024:09:17:57 +0000: Starting PostgREST 12.1...
2024-06-03 16:17:57 03/Jun/2024:09:17:57 +0000: Attempting to connect to the database...
2024-06-03 16:17:57 03/Jun/2024:09:17:57 +0000: Admin server listening on port 3001
2024-06-03 16:17:57 03/Jun/2024:09:17:57 +0000: Listening on port 3000
2024-06-03 16:17:57 Assertion failed: *(&once->n) != 4 (threads.c: k5_once: 564)
2024-06-03 16:17:58 03/Jun/2024:09:17:58 +0000: Starting PostgREST 12.1...
2024-06-03 16:17:58 03/Jun/2024:09:17:58 +0000: Attempting to connect to the database...
2024-06-03 16:17:58 03/Jun/2024:09:17:58 +0000: Admin server listening on port 3001
2024-06-03 16:17:58 03/Jun/2024:09:17:58 +0000: Listening on port 3000
2024-06-03 16:17:58 Assertion failed: *(&once->n) != 4 (threads.c: k5_once: 564)
2024-06-03 16:17:59 03/Jun/2024:09:17:59 +0000: Starting PostgREST 12.1...
2024-06-03 16:17:59 03/Jun/2024:09:17:59 +0000: Attempting to connect to the database...
2024-06-03 16:17:59 03/Jun/2024:09:17:59 +0000: Admin server listening on port 3001
2024-06-03 16:17:59 03/Jun/2024:09:17:59 +0000: Listening on port 3000
2024-06-03 16:17:59 Assertion failed: *(&once->n) != 4 (threads.c: k5_once: 564)
2024-06-03 16:18:01 03/Jun/2024:09:18:01 +0000: Starting PostgREST 12.1...
2024-06-03 16:18:01 03/Jun/2024:09:18:01 +0000: Attempting to connect to the database...
2024-06-03 16:18:01 03/Jun/2024:09:18:01 +0000: Admin server listening on port 3001
2024-06-03 16:18:01 03/Jun/2024:09:18:01 +0000: Listening on port 3000
2024-06-03 16:18:01 Assertion failed: *(&once->n) != 4 (threads.c: k5_once: 564)
2024-06-03 16:18:05 03/Jun/2024:09:18:05 +0000: Starting PostgREST 12.1...
2024-06-03 16:18:05 03/Jun/2024:09:18:05 +0000: Attempting to connect to the database...
2024-06-03 16:18:05 03/Jun/2024:09:18:05 +0000: Admin server listening on port 3001
2024-06-03 16:18:05 03/Jun/2024:09:18:05 +0000: Listening on port 3000
2024-06-03 16:18:05 Assertion failed: *(&once->n) != 4 (threads.c: k5_once: 564)
2024-06-03 16:18:12 03/Jun/2024:09:18:12 +0000: Starting PostgREST 12.1...
2024-06-03 16:18:12 03/Jun/2024:09:18:12 +0000: Attempting to connect to the database...
2024-06-03 16:18:12 03/Jun/2024:09:18:12 +0000: Admin server listening on port 3001
2024-06-03 16:18:12 03/Jun/2024:09:18:12 +0000: Listening on port 3000
2024-06-03 16:18:12 Assertion failed: *(&once->n) != 4 (threads.c: k5_once: 564)
```

Which makes Next.js unable to produce development output when developing using `pnpm dev`, and returns the following error in the console:
```sql
{
  code: 'PGRST002',
  details: null,
  hint: null,
  message: 'Could not query the database for the schema cache. Retrying.',
  digest: '4171135552'
}
```
and the error that prevented the development build output:
```sql
{
  message: 'An invalid response was received from the upstream server',
  digest: '1306904865'
}
```

**System information**
 - Version of OS: Windows 11 23H2 (Build 22631.3672)
 - Version of CLI: 1.172.2
 - Version of Docker: v4.30.0
 - Versions of services:
 
 ```
        SERVICE IMAGE      │        LOCAL         │  LINKED
  ─────────────────────────┼──────────────────────┼────────────
    supabase/postgres      │ 15.1.1.56            │ 15.1.1.56
    supabase/gotrue        │ v2.152.0             │ v2.152.0
    postgrest/postgrest    │ v12.1                │ v12.1
    supabase/realtime      │ v2.28.32             │ -
    supabase/storage-api   │ v1.2.1               │ v1.2.1
    supabase/edge-runtime  │ v1.53.3              │ -
    supabase/studio        │ 20240422-5cf8f30     │ -
    supabase/postgres-meta │ v0.80.0              │ -
    supabase/logflare      │ 1.4.0                │ -
    bitnami/pgbouncer      │ 1.20.1-debian-11-r39 │ -
    darthsim/imgproxy      │ v3.8.0               │ -
```

**Comment by vhpx** [comment]
![image](https://github.com/supabase/cli/assets/81307469/028d379b-c5b2-47d5-88bf-cbd9da709ff5)

It keeps restarting on its own, I'm significantly slowed down due to this bug.

**Comment by vhpx** [comment]
Update: reverted PostgREST to v12.0.2 and monitored for about 30 minutes, seems like the bug has been resolved the earlier version. I think PostgREST v12.1 isn't stable to be used yet for my development flow.

**Comment by sweatybridge** [comment]
Thanks for reporting this. I will ping PostgREST team to check if there's a fix.

**Comment by sweatybridge** [comment]
Does the error happen on your hosted project or just local?

**Comment by vhpx** [comment]
Looks like staging is unaffected, so I'm assuming it only happens on local for now. I'll closely monitor my hosted instance if it happens there.

**Comment by steve-chavez** [comment]
```
postgrest/postgrest    │ v12.1                │ v12.1
```

Hm, PostgREST hasn't yet released v12.1, check https://hub.docker.com/r/postgrest/postgrest/tags. Latest release is v12.0.3.

@sweatybridge Could you clarify from where is the v12.1 coming? 

Tried grepping for the code but I got this which says v12.0.1 https://github.com/supabase/cli/blob/c5febaf8c6dbcaeda44e85a12a66715bfc4809fd/internal/utils/misc.go#L33

**Comment by sweatybridge** [comment]
v12.1 is an alias for `devel` tag that's published only in supabase ECR and GHCR. Docker hub doesn't have this tag.

**Comment by steve-chavez** [comment]
Hm, this should be corrected then:

```
 postgrest/postgrest    │ v12.1                │ v12.1
```

It's misleading since it doesn't come from postgREST upstream.

> v12.1 is an alias for devel tag that's published only in supabase ECR and GHCR

@sweatybridge How can I introspect those dockerfiles?

---

```
2024-06-03 16:17:58 Assertion failed: *(&once->n) != 4 (threads.c: k5_once: 564)
```

This error is coming from kerberos([ref](https://github.com/krb5/krb5//blob/5f0023d5f05e95021a7caa1193f76f86871222ce/src/util/support/threads.c#L558-L565)), which is a C library. It could be an issue with how the image is built.

**Comment by sweatybridge** [comment]
Since user is having problem on windows and not hosted, this error might be only specific to amd64 image of PostgREST. The v12.1 tag is available here https://github.com/supabase/cli/pkgs/container/postgrest/223414607?tag=v12.1 

May be you can inspect it after docker pull ghcr.io/supabase/postgrest:v12.1

**Comment by guigzp** [comment]
Any fixes for that? I cant start my local environment with this error

**Comment by vhpx** [comment]
@guigzp for now, change the value in supabase/.temp/rest_version to `v12.0.2` and restart local cli, it should work as a temporary fix.

**Comment by steve-chavez** [comment]
This is already fixed upstream. It should be solved here after https://github.com/supabase/postgres/pull/1003 is merged.

**Comment by guigzp** [comment]
Changing supabase/.temp/rest_version to v12.0.2 solved but I had to use version 1.150.0 of the CLI as the latest was not working for me.

**Comment by empz** [comment]
I'm unable to use this as of today as the container keeps crashing (related: https://github.com/supabase/cli/issues/3550)

Can somebody address this issue? It's still happening. If it's a problem with upstream PostgREST then please revert the version to a stable version or let us do it ourselves.

**Comment by skogler** [comment]
I have got the same problem locally using Postgrest 12.1:

```
Assertion failed: *(&once->n) != 4 (threads.c: k5_once: 564)
```

Using the 12.1 image with SHA256 8cc243d7c2b887b3903a49aa849aedea53365ccfeeaf0001d59d11f6d26047ef

**Comment by steve-chavez** [comment]
>If it's a problem with upstream PostgREST

This was already solved in [v12.2.0](https://github.com/PostgREST/postgrest/releases/tag/v12.2.0), solution here is to upgrade. 

CLI already is on that version IIRC (maybe @sweatybridge can confirm). 

Perhaps this is a case of users having an outdated docker image locally.

**Comment by skogler** [comment]
Managed to fix it by:

- `supabase stop`
- removing all docker containers and volumes
- deleting`supabase/.temp` dir
- `supabase start`

I think it might work if you just delete the temp dir, since it contains the pinned versions
