### ISSUE TITLE
Local Project Link Request says update config.toml but no differences cited

### ISSUE THREAD

**Issue by sosensible** [supabase/cli#2539]
**Describe the bug**
Attempting to run `> supabase link` generated this exception.

```
Connecting to remote database...
Finished supabase link.
WARNING: Local config differs from linked project. Try updating supabase\config.toml
[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000
[api.tls]
enabled = false
```

**To Reproduce**
1. run `> supabase link`
2. enter the db password when requested
3. read the error message
4. check for differences there are none
5. look for docs to say what settings are in linked project, no known path to resolve
6. tried updating to current db version on prod site and repeating but same results

**Expected behavior**
Local dev to link with remote without a `WARNING:` that has not path to resolution.

**Screenshots**
n/a

**System information**
Rerun the failing command with `--create-ticket` flag.
 - Ticket ID: ... would not create ticket ...
 - Version of OS: Windows 11
 - Version of CLI: 1.183.5
 - Version of Docker: 27.0.3
 - Versions of services: 
 ```
        SERVICE IMAGE      │      LOCAL       │  LINKED
  ─────────────────────────┼──────────────────┼────────────
    supabase/postgres      │ 15.1.1.78        │ 15.1.1.78
    supabase/gotrue        │ v2.155.3         │ v2.155.3
    postgrest/postgrest    │ v12.2.2          │ v12.2.2
    supabase/realtime      │ v2.29.15         │ -
    supabase/storage-api   │ v1.6.8           │ v1.6.8
    supabase/edge-runtime  │ v1.54.10         │ -
    supabase/studio        │ 20240701-05dfbec │ -
    supabase/postgres-meta │ v0.83.2          │ -
    supabase/logflare      │ 1.4.0            │ -
    supabase/supavisor     │ 1.1.56           │ -
    darthsim/imgproxy      │ v3.8.0           │ -
```
**Additional context**
n/a

**Comment by hamzaakramdropslab** [comment]
> @sosensible did you find the solution to this problem

**Comment by sosensible** [comment]
We got it running but blocking some of the service containers from starting, but that is not functional as we expect to use some of those services.

**Comment by evris99** [comment]
Same for me with supabase-cli version 1.187.2

**Comment by empz** [comment]
Also experiencing this issue.
Supabase CLI 1.187.3

**Comment by plainpaul** [comment]
Same issue using: Supabase CLI 1.187.3

**Comment by plainpaul** [comment]
I'm somewhat new to supabase and even newer to supabase cli so pardon my ignorance. I didn't realize I could have a local dev instance when I started, so I built everything through a dashboard/SQL editor. To get it locally, is this where Project Link comes into play? Are there any workarounds to get this work bug fixed? Is there any way to output the toml file from Supabase's dashboard and update it that way?

**Comment by sweatybridge** [comment]
I can confirm this is a bug with detecting differences in remote and local config, which results in the printed message. However, seeing this message does not mean linking project failed. You can continue using supabase locally with cli despite config differences.

@plainpaul hope this clarifies.

**Comment by sweatybridge** [comment]
The config diff bug as been resolved in latest cli release.

**Comment by o1Suleyman** [comment]
> The config diff bug as been resolved in latest cli release.

no? I'm still getting it on the latest supabase-cli
![image](https://github.com/user-attachments/assets/4c0b943f-03e0-4784-9c7f-ec5b21760ab7)

**Comment by sweatybridge** [comment]
Could you show the entire terminal output, including the config diff?

To resolve this warning, you can update local config.toml to match the remote project.

**Comment by nicholasmartin** [comment]
> Could you show the entire terminal output, including the config diff?
> 
> To resolve this warning, you can update local config.toml to match the remote project.

Sorry I'm new to Supabase, where do you find the remote project config file in Supabase?

**Comment by AndryHTC** [comment]
Any news about that?

**Comment by Troopermaniac** [comment]
I'm getting the same issue. This is not fixed.

**Comment by buleagency** [comment]
Same here

**Comment by sweatybridge** [comment]
> it always says -additional_redirect_urls = ["https://127.0.0.1:3000"]. Even though I've removed that line.

Could you try setting `additional_redirect_urls = []` in config.toml instead?

**Comment by regexb** [comment]
It still shows it "differs from linked project:

```
Finished supabase link.
WARNING: Local config differs from linked project. Try updating supabase/config.toml
diff supabase/config.toml hkrljnqgrhdpzfcmjotc
--- supabase/config.toml
+++ hkrljnqgrhdpzfcmjotc
@@ -51,7 +51,6 @@
 [auth]
 enabled = true
 site_url = "http://localhost:3000"
-additional_redirect_urls = []
 jwt_expiry = 3600
 enable_refresh_token_rotation = true
 refresh_token_reuse_interval = 10
```

Note this still links successfully, so I'm not stuck. Just weird that it warns that I need to remove the line even when it's not set locally at all.

**Comment by Troopermaniac** [comment]
I found out the issue. Even if you made your project in a specified folder it will make a new config.toml in C:\Users\<yourcomputername>\supabase This is incredibly vague because it would have seemed that the original install path would have been the one used.

**Comment by sweatybridge** [comment]
@regexb I've pushed another fix for `additional_redirect_urls = []`. It should no longer report the difference when you run `npx supabase@beta link`.

Thanks for helping to debug this issue.

**Comment by kylerberry** [comment]
beta release fixes the issue for me

**Comment by kristiyann** [comment]
Still getting this issue even after using `npx supabase@beta link`

**Comment by APandzic** [comment]
Me too!

**Comment by agileminds-marvin** [comment]
Still getting the warning using npx supabase@beta link

WARNING: Local config differs from linked project. Try updating supabase/config.toml

- supabase@2.22.3

**Comment by AndryHTC** [comment]
Still not fixed.
I stick to the `deno.json + import.json`

**Comment by sweatybridge** [comment]
Could you share the config differences reported by cli?

**Comment by victorpergher** [comment]
same problem here

**Comment by lexcastro** [comment]
The same problem applies to me as well. Here my config differences reported by the CLI.

``` bash
> npx supabase link
Selected project: {project_id}
Enter your database password (or leave blank to skip):
Finished supabase link.
WARNING: Local config differs from linked project. Try updating supabase/config.toml
diff supabase/config.toml {project_id}
--- supabase/config.toml
+++{project_id}
@@ -94,9 +94,9 @@
 [auth.email]
 enable_signup = true
 double_confirm_changes = true
-enable_confirmations = false
+enable_confirmations = true
 secure_password_change = false
-max_frequency = "1s"
+max_frequency = "1m0s"
 otp_length = 6
 otp_expiry = 3600
 [auth.email.template]
```

**Comment by maurimtl** [comment]
I have CLI 2.22.12

it's just not applying the changes :(

WARNING: Local config differs from linked project. Try updating supabase/config.toml
diff supabase/config.toml [project-ref-redacted]
--- supabase/config.toml
+++ [project-ref-redacted]
@@ -53,8 +53,8 @@
 
 [auth]
 enabled = true
-site_url = "http://127.0.0.1:3000"
-additional_redirect_urls = ["https://127.0.0.1:3000"]
+site_url = "[redacted]"
+additional_redirect_urls = ["http://localhost:3000/*", "[redacted]*"]

**Comment by AndryHTC** [comment]
Why is this issue closed btw?

**Comment by JetUni** [comment]
I haven't linked my project in a while, but got a message when starting the services that my db version was out of date and that I needed to update by running `supabase link`, but now I'm stuck and I can't continue working on my project because of the message. Several of the lines that is says are different don't even exist in my config.toml file. I'm also on CLI v2.22.12. Here is the output I receive

```
diff supabase\config.toml <project-ref>
--- supabase\config.toml
+++ <project-ref>
@@ -2,7 +2,7 @@

 [api]
 enabled = true
-schemas = ["public", "graphql_public"]
+schemas = ["public", "graphql_public", "<schema-1>", "<schema-2>"]
 extra_search_path = ["public", "extensions"]
 max_rows = 1000
 port = 54321
@@ -53,9 +53,9 @@

 [auth]
 enabled = true
-site_url = "http://127.0.0.1:3000"
-additional_redirect_urls = ["https://127.0.0.1:3000"]
-jwt_expiry = 3600
+site_url = "<url>"
+additional_redirect_urls = ["<url-1>", "<url-2>", "<url-3>", "<url-4>"]
+jwt_expiry = 36000
 enable_refresh_token_rotation = true
 refresh_token_reuse_interval = 10
 enable_manual_linking = false
@@ -68,9 +68,9 @@
 service_role_key = ""
 [auth.rate_limit]
 anonymous_users = 30
-token_refresh = 150
-sign_in_sign_ups = 30
-token_verifications = 30
+token_refresh = 15
+sign_in_sign_ups = 3
+token_verifications = 3
 email_sent = 2
 sms_sent = 30
 [auth.hook]
@@ -77,8 +77,8 @@
 [auth.mfa]
 max_enrolled_factors = 10
 [auth.mfa.totp]
-enroll_enabled = false
-verify_enabled = false
+enroll_enabled = true
+verify_enabled = true
 [auth.mfa.phone]
 enroll_enabled = false
 verify_enabled = false
@@ -94,11 +94,11 @@
 [auth.email]
 enable_signup = true
 double_confirm_changes = true
-enable_confirmations = false
+enable_confirmations = true
 secure_password_change = false
-max_frequency = "1s"
-otp_length = 6
-otp_expiry = 3600
+max_frequency = "1m0s"
+otp_length = 6
+otp_expiry = 600
 [auth.email.template]
 [auth.sms]
 enable_signup = false
```

**Comment by albertocubeddu** [comment]
+1

**Comment by TheUltDev** [comment]
Had to comment out [auth] configs to be able to link, the diff indicated the the secret hashes were causing the issue.

**Comment by seanperez29** [comment]
I'm receiving this error. Is there still no resolution to this?

**Comment by mauro-n** [comment]
Same error

**Comment by AndryHTC** [comment]
P1 priority
Closed 1 year ago (https://github.com/supabase/cli/pull/2558)
Still not solved

**Comment by abbott** [comment]
@sweatybridge hi, any ETA on bug fix?

🚑 I debugged the CLI and got the following config working for `2.33.1` 🚀

```toml

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = []
jwt_expiry = 3600
enable_refresh_token_rotation = true
refresh_token_reuse_interval = 10
[auth.mfa]
max_enrolled_factors = 10
[auth.mfa.totp]
enroll_enabled = false
verify_enabled = false
[auth.mfa.phone]
enroll_enabled = false
verify_enabled = false
template = "Your code is {{ .Code }}"
max_frequency = "5s"
[auth.mfa.web_authn]
enroll_enabled = false
verify_enabled = false
[auth.email]
double_confirm_changes = true
enable_confirmations = true
secure_password_change = false
max_frequency = "1m0s"
otp_length = 6
otp_expiry = 3600


```

If you receive additional validation output, simply update the values to match. The above config is boilerplate for a new project.

**Comment by marcospgp** [comment]
so I just got this today, I'm not sure why the config differs if I just ran `bun supabase link` (isn't it supposed to pull the config? I had no local `config.toml` before)

```
Finished supabase link.
WARNING: Local config differs from linked project. Try updating supabase/config.toml
diff supabase/config.toml swumhmrsxdoeoyhbrdua
--- supabase/config.toml
+++ swumhmrsxdoeoyhbrdua
@@ -2,8 +2,8 @@
 
 [api]
 enabled = true
-schemas = ["public", "graphql_public"]
-extra_search_path = ["public", "extensions"]
```

are we expected to manually update a `config.toml` file that was just created by a CLI command? I am kind of confused aha

**Comment by jmwind** [comment]
This is a blocker and a regression. By definition, it's very likely that your local config.toml configuration will different from what you're linking. 

We link in our GitHub action to deploy the latest migrations. We run:

```
npx supabase@latest link --project-ref $DEVELOPMENT_PROJECT_ID
npx supabase@latest db push
```

This is failing with the WARNING: Local config differs. We are stuck.

**Comment by sweatybridge** [comment]
Ok I've reopened this to rethink how to manage the config diff properly.

The link output is just a warning btw. If your CI is failing, it's probably due to something else.

**Comment by jmwind** [comment]
You're right. @sweatybridge the other error was buried further down in the logs 🤦 
But the warning will always happen for our usecase of doing a `db push` from CI.
