### ISSUE TITLE
Self Hosted- 404 API Calls for Default Settings

### ISSUE THREAD

**Issue by kshitijdomadia** [supabase/cli#2834]
**The bug**
I recently acquired a new MacBook and attempted to create a new user using the Supabase Studio. However, the fields began to display as “inactive” for a few seconds before reverting to an “active” state, allowing me to enter the fields and vice versa every few seconds. I opened Dev tools to find failed 404 requests to default/settings running **indefinitely**. It seems to initiate from project/default.

Response Headers:
`HTTP/1.1 404 Not Found
X-Frame-Options: DENY
X-Content-Type-Options: no-sniff
Content-Security-Policy: frame-ancestors 'none';
Referrer-Policy: strict-origin-when-cross-origin
Cache-Control: private, no-cache, no-store, max-age=0, must-revalidate
X-Powered-By: Next.js
ETag: "1sp144z4gi5p5"
Content-Type: text/html; charset=utf-8
Vary: Accept-Encoding
Content-Encoding: gzip
Date: Tue, 05 Nov 2024 14:08:42 GMT
Connection: keep-alive
Keep-Alive: timeout=5
Transfer-Encoding: chunked`

Request Headers:
`GET /api/projects/default/settings HTTP/1.1
Accept-Encoding: gzip, deflate, br, zstd
Accept-Language: en-US,en;q=0.9
Connection: keep-alive
Host: 127.0.0.1:54323
Referer: http://127.0.0.1:54323/project/default/auth/users
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-origin
Sec-GPC: 1
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
accept: application/json
content-type: application/json
sec-ch-ua: "Chromium";v="130", "Brave";v="130", "Not?A_Brand";v="99"
sec-ch-ua-mobile: ?0
sec-ch-ua-platform: "macOS"
x-request-id: 3cb39363-4ec9-4a84-9991-cbade7c0f09d`

**To Reproduce**
1. Run supabase start with a normal toml file

**Expected behavior**
Needs to allow me to create a user, and not have these errors popping up in dev kit

**Screenshots**

<img width="556" alt="Screenshot 2024-11-05 at 6 06 10 PM" src="https://github.com/user-attachments/assets/f3b08167-30f9-488d-86c4-11d1196436a8">

Initiator chain:

<img width="500" alt="Screenshot 2024-11-05 at 6 07 32 PM" src="https://github.com/user-attachments/assets/591925c9-ab29-431f-8267-04006e32ddcc">

**System information**
 - Version of OS: MacOS 15.1 Sequoia
 - Version of CLI: 1.215.0
 - Version of Docker: 4.34.3

**Additional context**
If applicable, add any other context about the problem here.
 - Browser- Safari and Brave

**Comment by itsmikesharescode** [comment]
I am experiencing this it was all working yesterday i am using linux mint

**Comment by kshitijdomadia** [comment]
> I am experiencing this it was all working yesterday i am using linux mint

Strange. Did you update supabase/docker?

**Comment by itsmikesharescode** [comment]
> > I am experiencing this it was all working yesterday i am using linux mint
> 
> Strange. Did you update supabase/docker recently?

Yea i do auto update

**Comment by mlmassey** [comment]
I'm experiencing the same issue.  Stuck and cannot use the web interface currently

**Comment by kshitijdomadia** [comment]
Definitely something broke with the newer version. I found out that this was definitely an issue with supabase and not docker by running the npm version of the cli @ v1.172.2 ie. #2335

This was the working version on my fedora workstation, which also seems to work on my mac now.

**Comment by kshitijdomadia** [comment]
@joshenlim thanks for taking this forward. Do you know when this patch will be released?

**Comment by joshenlim** [comment]
> @joshenlim thanks for taking this forward. Do you know when this patch will be released?

we're currently looking to get this out atm! will keep you guys updated 🙂 sorry about this too for the disruption 🙏 🙏

**Comment by itsmikesharescode** [comment]
Is this already fix?

**Comment by sweatybridge** [comment]
Yup, this has been addressed in beta release channel.

```
npx supabase@beta start
```

**Comment by itsmikesharescode** [comment]
> Yup, this has been addressed in beta release channel.
> 
> ```
> npx supabase@beta start
> ```

thank you! that was fast!

**Comment by itsmikesharescode** [comment]
![image](https://github.com/user-attachments/assets/e4572b7e-00ef-4f20-b996-92f703acbeea)

still unable to use it

**Comment by antonsarg** [comment]
I'm still encountering API endpoint errors on the beta, even though the settings call appears to be working fine now. I was hopeful this would resolve the other endpoint issues as well. However, I noticed that an issue has already been opened for this [#30227](https://github.com/supabase/supabase/issues/30227).

**Comment by ivasilov** [comment]
@antonsarg @itsmikesharescode this has been fixed in the CLI v1.218.1, please update your versions and let us know if you still have this issue.
