### ISSUE TITLE
`supabase start` fails with error 'Container ... is restarting, wait until the container is running'

### ISSUE THREAD

**Issue by kaheahendrickson** [supabase/cli#286]
# Bug report

## Describe the bug

`supabase start` fails and produces error 'Error: Error response from daemon: Container 39ecdf... is restarting, wait until the container is running'

## To Reproduce

1. Run `supabase init`
2. Run `supabase start`

## Expected behavior

Supabase starts.

## System information

- OS: macOS
- Docker: 20.10.16
- Supabase Cli: 0.26.2
- supabase/deno-relay: v1.2.0
- supabase/gotrue: v2.6.18
- supabase/phadmin-schema-diff: cli-0.0.4
- supabase/postgres: 14.1.0.21
- supabase/postgres-meta: v0.33.2
- supabase/realtime v0.22.4
- supabase/storage-api: v0.15.0
- supabase/studio: latest

## Additional context

There is a container created from image 'supabase/postgres' but as quick as it appears it is deleted and I can't access the logs.

Also i noticed that `supabase init` only creates a single file 'supabase/config.toml'. The docs https://supabase.com/docs/guides/local-development mention that a 'supabase/seed.sql' is created by `supabase init`. Should `supabase init` be creating more files?

**Comment by kaheahendrickson** [comment]
I was able to fix this by deleting all containers and volumes then restarting supabase.

**Comment by psteinroe** [comment]
@egor-romanov could we reopen this? I am suddenly experiencing this in a GitHub Action. Nothing changes, just from one action run to the other it started to always throw this error...

**Comment by aslakhellesoy** [comment]
I'm seeing the same thing

**Comment by psteinroe** [comment]
I have opened an urgent ticket with the supabase support since this is blocking us from running any ci.

**Comment by sweatybridge** [comment]
Hello, are you able to pin the CLI version on GHA to a previously working one for the time being? Possibly 1.4.7

You can refer to a working example here https://github.com/supabase/setup-cli

We will look into the issue soon to fix it in the next release.

**Comment by aslakhellesoy** [comment]
> Hello, are you able to pin the CLI version on GHA to a previously working one for the time being? Possibly 1.4.7

Using a previously working version doesn't seem to work.
When this started failing I was on 1.4.2. I upgraded to 1.5.0 and have the same error.

**Comment by psteinroe** [comment]
Same here! Same problem occurs after downgrading. Also, it worked before on 1.5.0, I did not upgrade or change anything. It suddenly stopped working.

**Comment by egor-romanov** [comment]
Thank you for reporting this. I was trying to reproduce it, but no luck.

Can you confirm that this problem only occurs on CI runners?

**Comment by aslakhellesoy** [comment]
> Can you confirm that this problem only occurs on CI runners?

Only on GitHub Actions for me. Works fine locally.

**Comment by psteinroe** [comment]
> Can you confirm that this problem only occurs on CI runners?

Same here. I removed my docker image cache locally, but it downloads the images and launches the containers as expected.

GH runner versions are also exactly the same...
```
Current runner version: '2.296.2'
Operating System
  Ubuntu
  20.04.5
  LTS
Runner Image
  Image: ubuntu-20.04
  Version: 20220922.2
  Image Release: https://github.com/actions/runner-images/releases/tag/ubuntu20%2F20220922.2
Runner Image Provisioner
  1.0.0.0-main-20220916-1
```

**Comment by aslakhellesoy** [comment]
I've created https://github.com/supabase/setup-cli/pull/59 which I hope will reproduce the problem. Can someone from supabase please approve running the workflows on this PR?

**Comment by sweatybridge** [comment]
We found the root cause: the [supabase/postgres](https://hub.docker.com/r/supabase/postgres/tags) image that the CLI depends on was updated 10h ago with an arm64 build. Unfortunately the multi-arch manifest was not updated correctly, resulting in arm64 images being pulled on x86 machines. This broke GHA and anyone trying to `supabase start` on a fresh x86 computer without any locally cached docker images.

We are still looking into fixing the issue and will post an update once that's resolved.

**Comment by aslakhellesoy** [comment]
It sounds like `supabase-cli` doesn't pin the versions of the docker images it fires up. If an update to `supabase/postgres` can break existing installations this way, does this mean the `:latest` docker image is downloaded rather than a specific version?

How can we have [reproducible builds](https://en.wikipedia.org/wiki/Reproducible_builds) if this is the case?

Have you considered pinning the docker image versions?

**Comment by aslakhellesoy** [comment]
I see on [supabase/postgres](https://hub.docker.com/r/supabase/postgres/tags) that [14.1.0.71](https://hub.docker.com/layers/supabase/postgres/14.1.0.71/images/sha256-90119a062b2072d2a5c0b297059cec8c0bc90df76c22c6f9c455320a465a504d?context=explore) was pushed, but `latest` is still pointing to an older version ([14.1.0.61](https://hub.docker.com/layers/supabase/postgres/14.1.0.61/images/sha256-33d69ef6d6941b411e1e96950735e2844eda6b9477b95160f155e9c6d51d22d6?context=explore)).

Maybe an opportunity to review your release process?

**Comment by darora** [comment]
Hey folks-sorry about that; this was an unintended side-effect of my work on getting arm64 images out. I made the mistaken assumption that the repo was immutable (something we do by default), but it looks like public ECR repos don't support immutability. To close out this thread:

- I'm re-uploading the x86 image, and it should fix fresh pulls once that completes (in an hour or so)
- we'll fix the multi-arch build to avoid running into this again
- @sweatybridge is working on a new CLI build that uses a newer release of postgres, which should avoid any issues with the arm image being picked up off a cache and causing issues

@aslakhellesoy towards your specific concerns:

- we haven't been using `latest` (or any other similar mutable tags) in quite a while; it's been left there to avoid breaking anyone that was using it (and bumping it up _would_ break them). No good options here, imo this was the less harmful one.
- the supabase-cli does pin the images involved ( c.f. internal/utils/misc.go )

**Comment by sweatybridge** [comment]
We have released CLI v1.5.1 which uses postgres 14.1.0.71 and I have verified `supabase start` is [working on GHA](https://github.com/supabase/cli/actions/runs/3155524593/jobs/5134279598).

We will update 14.1.0.66 image later to fix older CLI versions.

**Comment by aslakhellesoy** [comment]
Thanks a lot for the quick turnaround to fix this. I'm no longer getting the previous error, but I am now getting another one. Here is my GitHub Action config:

```yaml
- name: Install Supabase
  uses: supabase/setup-cli@v1.0.2
  with:
    version: 1.5.2

- name: Start Supabase
  run: supabase start
  env:
    # https://github.com/supabase/cli/issues/419#issuecomment-1232025865
    SUPABASE_INTERNAL_IMAGE_REGISTRY: docker.io
```

I'm getting this error:

```
Pulling images...
Pulling from supabase/postgres...
Pulling from supabase/postgres...
Pulling from supabase/postgres...
Pulling from supabase/postgres...
Pulling from supabase/postgres...
Pulling from supabase/postgres...
Pulling from supabase/postgres...
Pulling from supabase/postgres...
Pulling from supabase/postgres...
Pulling from supabase/postgres...
Pulling from supabase/postgres...
Starting database...
Restoring branches...
Setting up initial schema...
Applying migration 20220429171120_create_profiles.sql...
Applying migration 20220429223619_rls-and-trigger.sql...
Applying supabase/seed.sql...
Starting containers...
Failed to restart storage-api: Error response from daemon: No such container: supabase_storage_server
Error: Error response from daemon: No such image: kong:2.8.1
```

If I remove the `SUPABASE_INTERNAL_IMAGE_REGISTRY` environment variable I get a similar error:

```
Error: Error response from daemon: No such image: public.ecr.aws/t3w2s2c9/kong:2.8.1
```

Any idea why `kong:2.8.1` is not found? I can see it here: https://hub.docker.com/_/kong

**Comment by aslakhellesoy** [comment]
It looks to me like `supabase 1.5.2` isn't pulling all the images it needs. My workaround for now is to explicitly pull all the images before `supabase start`:

```yaml
- name: Start Supabase
  run: |
    docker pull public.ecr.aws/t3w2s2c9/postgres:14.1.0.71 &&
    docker pull public.ecr.aws/t3w2s2c9/postgres:14.1.0.66 &&
    docker pull public.ecr.aws/t3w2s2c9/storage-api:v0.20.1 &&
    docker pull public.ecr.aws/t3w2s2c9/postgres-meta:v0.45.0 &&
    docker pull public.ecr.aws/t3w2s2c9/gotrue:v2.15.3 &&
    docker pull public.ecr.aws/t3w2s2c9/studio:v0.1.0 &&
    docker pull public.ecr.aws/t3w2s2c9/pgadmin-schema-diff:cli-0.0.5 &&
    docker pull public.ecr.aws/t3w2s2c9/kong:2.8.1 &&
    docker pull public.ecr.aws/t3w2s2c9/inbucket:3.0.3 &&
    docker pull public.ecr.aws/t3w2s2c9/postgrest:v9.0.1.20220717 &&
    docker pull public.ecr.aws/t3w2s2c9/realtime:v0.22.7 &&
    supabase start
```

**Comment by sweatybridge** [comment]
Sorry I accidentally renamed a bunch of images in #488. Should be fixed in 1.5.3

**Comment by aslakhellesoy** [comment]
It's still broken. My GitHub Action:

```yaml
- name: Install Supabase
  uses: supabase/setup-cli@v1.0.2
  with:
    version: 1.5.3

- name: Start Supabase
  run: supabase start
```

The error:

```
Applying supabase/seed.sql...
Starting containers...
Error: Error response from daemon: No such image: public.ecr.aws/t3w2s2c9/postgres-meta:v0.45.0
Error: Process completed with exit code 1.
```

Might I suggest that rather than relying on users to test that `supabase start` works on GitHub Actions, you have your own CI somewhere that verifies this and alerts you when it breaks? And maybe automate the parts of your release process that is prone to human error?

I've managed to make it start with a new workaround (my previous workaround spuriously fails with `toomanyrequests: Rate exceeded` - as mentioned in https://github.com/supabase/cli/issues/419#issuecomment-1232025865)

```yaml
- name: Start Supabase
  run: |
    docker pull postgres:14.1.0.71 &&
    docker pull postgres:14.1.0.66 &&
    docker pull storage-api:v0.20.1 &&
    docker pull postgres-meta:v0.45.0 &&
    docker pull gotrue:v2.15.3 &&
    docker pull studio:v0.1.0 &&
    docker pull pgadmin-schema-diff:cli-0.0.5 &&
    docker pull kong:2.8.1 &&
    docker pull inbucket:3.0.3 &&
    docker pull postgrest:v9.0.1.20220717 &&
    docker pull realtime:v0.22.7 &&
    supabase start
  env:
    # https://github.com/supabase/cli/issues/419#issuecomment-1232025865
    SUPABASE_INTERNAL_IMAGE_REGISTRY: docker.io
```

**Comment by sweatybridge** [comment]
> Error: Error response from daemon: No such image: public.ecr.aws/t3w2s2c9/postgres-meta:v0.45.0

This appears to be a new ephemeral error rather than a regression. Out of 131 `supabase start` commands we [ran from CI](https://github.com/supabase/setup-cli/actions/workflows/start.yml) on 1 Oct, 41 failed with a missing image error. After releasing v1.5.4, we ran 97 tests on 2 Oct and all of them succeeded. This also fixes rate limit error when pulling from ECR.

> Might I suggest that rather than relying on users to test that supabase start works on GitHub Actions, you have your own CI somewhere that verifies this and alerts you when it breaks?

Thanks for the feedback. We have since added a few automated tests to prevent regression.
1. CI workflow in [cli repo](https://github.com/supabase/cli/blob/main/.github/workflows/ci.yml#L44) now tests `supabase start` on each PR and merge to main
2. CLI Start workflow in [setup-cli](https://github.com/supabase/setup-cli/blob/main/.github/workflows/start.yml#L10) repo runs `supabase start` twice a day on version 1.5.4 and 1.0.0

> And maybe automate the parts of your release process that is prone to human error?

We have also refactored the image pulling code to make it less prone human error. We now define an [array of docker images](https://github.com/supabase/cli/blob/main/internal/utils/misc.go#L43) and call the same function to pull each one.

**Comment by brahmveda-shreya** [comment]
installed supabase cli with all dependecies like docker and all but when i run 

supabase start (command)

docker container is created and  inbetween something going wrong and stop container and not working and give me error 

-------------------------------------------------
::internal_events::api: API server running. address=0.0.0.0:9001 playground=http://0.0.0.0:9001/playground
                    2024-10-23T09:12:02.412007Z  INFO vector::app: All sources have finished.
       2024-10-23T09:12:02.412010Z  INFO vector: Vector has stopped.
                                                                    2024-10-23T09:12:02.413354Z  INFO vector::topology::running: Shutting down... Waiting on running components. remaining_components="logflare_auth, logflare_kong, logflare_db, logflare_realtime, logflare_functions, logflare_rest, logflare_storage" time_remaining="59 seconds left"
  Stopping containers...
supabase_vector_test_spabase container is not ready: unhealthy
Try rerunning the command with --debug to troubleshoot the error.

---------------------------------------------------------


give me error container is unhealthy. I followed all steps but it's working in refernce video but not wrok for me.
if some one getting same issue please help me for resolve this.
