### ISSUE TITLE
failed to connect to postgres: failed to connect to `host=db.[id].supabase.co user=postgres database=postgres`: dial error (dial tcp [2406:da14:271:9903:c1bf:5f4c:ff8a:9e0c]:5432: connect: no route to host)

### ISSUE THREAD

**Issue by eelyhtomit** [supabase/cli#3318]
**Describe the bug**
I have been using Supabase Cli to push migration to remote db with zero issues, until all the sudden I was not able to do that. I can still link to different projects within the same account but now commands such as `supabase db push --link` `supabase migrations list` throw an error as seen in title.

```
Supabase CLI 2.19.7
Connecting to remote database...
2025/03/18 21:28:29 Connect Start: tcp [2406:da14:271:9903:c1bf:5f4c:ff8a:9e0c]:5432
2025/03/18 21:28:29 Connect Error: tcp [2406:da14:271:9903:c1bf:5f4c:ff8a:9e0c]:5432 dial tcp [2406:da14:271:9903:c1bf:5f4c:ff8a:9e0c]:5432: connect: no route to host

```

**Comment by davbauer** [comment]
Experiencing the same issue in my github actions workflow. Several retries resulted in the same outcome.
The workflow ran for more than a year without any of these kind of issues.


Shortened log output:

```bash
Run supabase link --project-ref $SUPABASE_PROJECT_ID --debug
Supabase CLI 2.19.7

...(abbreviated logs)...

025/03/18 12:39:44 Connect Error: tcp [2600:1f18:2e13:9d0b:5cb9:1ef6:7858:9c8e]:5432 dial tcp [2600:1f18:2e13:9d0b:5cb9:1ef6:7858:9c8e]:5432: connect: network is unreachable
failed to connect to postgres: failed to connect to `host=db.***.supabase.co user=postgres database=postgres`: dial error (dial tcp [2600:1f18:2e13:9d0b:5cb9:1ef6:7858:9c8e]:5432: connect: network is unreachable)
```

**Comment by jernej555** [comment]
Experienced same behavior in last 30 minutes (no prior issues on this flow)


```
Run supabase link --project-ref $SUPABASE_PROJECT_ID --debug
Supabase CLI 2.19.7

...(abbreviated logs)...
2025-03-18T12:55:09.2239336Z Connecting to remote database...
2025-03-18T12:55:09.2446375Z failed to connect to postgres: failed to connect to `host=db.***.supabase.co user=postgres database=postgres`: dial error (dial tcp [2a05:d014:1c06:5f14:4987:ec54:c7e3:3f59]:5432: connect: network is unreachable)
2025-03-18T12:55:09.2448818Z Try rerunning the command with --debug to troubleshoot the error.
```

**Comment by Axolem** [comment]
Experiencing the same issue, tried to use different versions of the cli, the issue persists.

`
$ npx supabase@2.20.2 link
Selected project: wspyogpliv....
Enter your database password (or leave blank to skip):
Connecting to remote database...
failed to connect to postgres: failed to connect to `host=db.wspyogplivbbcnisxuiq.supabase.co user=postgres database=postgres`: dial error (timeout: dial tcp [2a05:d01c:30c:9d01:b8b5:407c:7cfa:58ec]:5432: i/o timeout)
Try rerunning the command with --debug to troubleshoot the error.

...alert/backend (rewrite)
$ npx supabase@2.15.8 link
Need to install the following packages:
supabase@2.15.8
Ok to proceed? (y) y

Selected project: wspyogpliv....
Enter your database password (or leave blank to skip):
Connecting to remote database...
failed to connect to postgres: failed to connect to `host=db.wspyogplivbbcnisxuiq.supabase.co user=postgres database=postgres`: dial error (timeout: dial tcp [2a05:d01c:30c:9d01:b8b5:407c:7cfa:58ec]:5432: i/o timeout)
Try rerunning the command with --debug to troubleshoot the error.
`

**Comment by JorSoi** [comment]
Same issue on my end using Gitub Actions. I updated supabase package from `2.15.8` to `2.19.7 `
Supabase doesnt let me link to my remote project, while throwing this error during `- run: supabase link --project-ref $SUPABASE_PROJECT_ID`

```
...(abbreviated logs)...
2025/03/18 13:26:17 Connect Start: tcp [2a05:d014:1c06:5f0c:ce66:2607:a46b:bfb4]:5432
2025/03/18 13:26:17 Connect Error: tcp [2a05:d014:1c06:5f0c:ce66:2607:a46b:bfb4]:5432 dial tcp [2a05:d014:1c06:5f0c:ce66:2607:a46b:bfb4]:5432: connect: network is unreachable
2025/03/18 13:26:17 Connect Start: tcp [2a05:d014:1c06:5f0c:ce66:2607:a46b:bfb4]:5432
2025/03/18 13:26:17 Connect Error: tcp [2a05:d014:1c06:5f0c:ce66:2607:a46b:bfb4]:5432 dial tcp [2a05:d014:1c06:5f0c:ce66:2607:a46b:bfb4]:5432: connect: network is unreachable
failed to connect to postgres: failed to connect to `host=db.***.supabase.co user=postgres database=postgres`: dial error (dial tcp [2a05:d014:1c06:5f0c:ce66:2607:a46b:bfb4]:5432: connect: network is unreachable)
```

**Comment by masda70** [comment]
Same issue with Github Actions and Supabase CLI 2.19.7 (installed using supabase/setup-cli@v1 with version: latest).

EDIT: Apparently Supabase team is already aware and looking into it
https://github.com/orgs/supabase/discussions/17817#discussioncomment-12538898

**Comment by spencer-rafada** [comment]
Same issue. Wasn't sure where to post the issue, but now I know! Thanks Supabase Staff!

**Comment by baresi687** [comment]
Was getting connect: network is unreachable. 
Now I'm getting 
`Authorization failed for the access token and project ref pair: {"message":"Cannot GET /***/***/***/***?reveal=false"}`

**Comment by JorSoi** [comment]
Also getting an authorization error now : 

```
Supabase CLI 2.19.7
2025/03/18 15:02:20 DNS Start: {Host:api.supabase.com}
2025/03/18 15:02:20 DNS Done: {Addrs:[{IP:[17](https://github.com/JorSoi/FriendsCodes-New/actions/runs/13926502161/job/38972336389#step:4:18)2.67.23.199 Zone:} {IP:104.22.2.252 Zone:} {IP:104.22.3.252 Zone:} {IP:2606:4700:10::6816:2fc Zone:} {IP:2606:4700:10::6816:3fc Zone:} {IP:2606:4700:10::ac43:17c7 Zone:}] Err:<nil> Coalesced:false}
2025/03/[18](https://github.com/JorSoi/FriendsCodes-New/actions/runs/13926502161/job/38972336389#step:4:19) 15:02:20 Connect Start: tcp 172.67.23.199:443
2025/03/18 15:02:20 Connect Done: tcp 172.67.23.199:443
2025/03/18 15:02:20 TLS Start
2025/03/18 15:02:20 TLS Done: {Version:772 HandshakeComplete:true DidResume:false CipherSuite:4865 NegotiatedProtocol:h2 NegotiatedProtocolIsMutual:true ServerName:api.supabase.com PeerCertificates:[0xc0003ac588 0xc0003ad088 0xc0003ad608] VerifiedChains:[[0xc0003ac588 0xc0003ad088 0xc0007a5b88] [0xc0003ac588 0xc0003ad088 0xc0003ad608 0xc0007a6108]] SignedCertificateTimestamps:[] OCSPResponse:[48 130 1 20 10 1 0 160 130 1 13 48 130 1 9 6 9 43 6 1 5 5 7 48 1 1 4 129 251 48 129 248 48 129 158 162 22 4 20 144 1[19](https://github.com/JorSoi/FriendsCodes-New/actions/runs/13926502161/job/38972336389#step:4:20) 146 53 103 196 255 168 204 169 230 123 217 128 121 123 204 147 249 56 24 15 50 48 50 53 48 51 49 54 49 50 49 54 51 49 90 48 115 48 113 48 73 48 9 6 5 43 14 3 2 26 5 0 4 [20](https://github.com/JorSoi/FriendsCodes-New/actions/runs/13926502161/job/38972336389#step:4:21) 185 190 213 241 166 30 64 178 65 150 176 194 158 126 26 157 139 252 181 32 4 20 144 119 146 53 103 196 255 168 204 169 230 123 [21](https://github.com/JorSoi/FriendsCodes-New/actions/runs/13926502161/job/38972336389#step:4:22)7 128 121 123 204 147 249 56 2 16 5 63 [22](https://github.com/JorSoi/FriendsCodes-New/actions/runs/13926502161/job/38972336389#step:4:23)2 170 28 52 166 77 14 155 138 65 196 91 40 38 128 0 24 15 50 48 50 53 48 51 49 54 49 50 49 54 51 49 90 160 17 24 15 50 48 50 53 48 51 50 51 49 49 49 54 51 48 90 48 10 
2025/03/18 15:02:20 Sent Header: :authority [api.supabase.com]
2025/03/18 15:02:20 Sent Header: :method [GET]
2025/03/18 15:02:20 Sent Header: :path [/v1/projects/***]
2025/03/18 15:02:20 Sent Header: :scheme [https]
2025/03/18 15:02:20 Sent Header: authorization [***
2025/03/18 15:02:20 Sent Header: user-agent [SupabaseCLI/2.19.7]
2025/03/18 15:02:20 Sent Header: accept-encoding [gzip]
2025/03/18 15:02:20 Send Done
2025/03/18 15:02:20 Recv First Byte
2025/03/18 15:02:20 Sent Header: :authority [api.supabase.com]
2025/03/18 15:02:20 Sent Header: :method [GET]
2025/03/18 15:02:20 Sent Header: :path [/v1/projects/***/api-keys?reveal=false]
2025/03/18 15:02:20 Sent Header: :scheme [https]
2025/03/18 15:02:20 Sent Header: authorization [***
2025/03/18 15:02:20 Sent Header: user-agent [SupabaseCLI/2.19.7]
2025/03/18 15:02:20 Sent Header: accept-encoding [gzip]
2025/03/18 15:02:20 Send Done
2025/03/18 15:02:20 Recv First Byte
Authorization failed for the access token and project ref pair: {"message":"Cannot GET /v1/projects/***/api-keys?reveal=false"}
```

**Comment by JorSoi** [comment]
Update: It finally works again. Thanks @sweatybridge !

**Comment by davbauer** [comment]
Fixed for my case too! Thanks for the team resolving this.

**Comment by spencer-rafada** [comment]
Will this issue be the same here `failed SASL auth (invalid SCRAM server-final-message received from server)`?

**Comment by jernej555** [comment]
Fixed for my case too! Thanks for the team resolving this.

**Comment by kevcodez** [comment]
In case you are still running into issues, rerun `supabase link` command - that should resolve it

**Comment by crro** [comment]
I'm still getting this issue with `network is unreachable` in my local env and in my github action. Is there anything I need to do on the github action to fix this? Currently this look what my migration looks like: 

```
jobs:
  deploy:
    runs-on: ubuntu-latest
    name: migrate db
    concurrency: migrate-group-staging
    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      SUPABASE_DB_PASSWORD: ${{ secrets.SUPABASE_DB_PASSWORD_STAGING }}
      SUPABASE_PROJECT_ID: ${{ secrets.SUPABASE_PROJECT_ID_STAGING }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Install supabase
      uses: supabase/setup-cli@v1
    - name: Link project
      working-directory: ./versive_db
      run: supabase link --project-ref $SUPABASE_PROJECT_ID
    - name: Run migrations
      working-directory: ./versive_db
      run: supabase db push
```

**Comment by kevcodez** [comment]
> I'm still getting this issue with `network is unreachable` in my local env and in my github action. Is there anything I need to do on the github action to fix this? Currently this look what my github action migration looks like:
> 
> ```
> jobs:
>   deploy:
>     runs-on: ubuntu-latest
>     name: migrate db
>     concurrency: migrate-group-staging
>     env:
>       SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
>       SUPABASE_DB_PASSWORD: ${{ secrets.SUPABASE_DB_PASSWORD_STAGING }}
>       SUPABASE_PROJECT_ID: ${{ secrets.SUPABASE_PROJECT_ID_STAGING }}
>     steps:
>     - name: Checkout code
>       uses: actions/checkout@v4
>     - name: Install supabase
>       uses: supabase/setup-cli@v1
>     - name: Link project
>       working-directory: ./versive_db
>       run: supabase link --project-ref $SUPABASE_PROJECT_ID
>     - name: Run migrations
>       working-directory: ./versive_db
>       run: supabase db push
> ```

Have you checked in any files of the `supabase/.temp` directory in your repo?

Have you tried resetting your GH action cache?

Could you post the full logs to show which URL it is trying to connect to?

**Comment by crro** [comment]
Locally:
```
crro@Davids-MacBook-Pro-10 versive_db % npx supabase --version
2.19.7
crro@Davids-MacBook-Pro-10 versive_db % rm -rf supabase/.temp
```
and then when running npx supabase link --project-ref <PROJECT-ID> I see it connect to an IPv4 which from this other bug looks like the are all deprecated (https://github.com/orgs/supabase/discussions/17817)?
Running the command in debug mode
```
crro@Davids-MacBook-Pro-10 versive_db % npx supabase link --project-ref <PROJECT_ID> --password
Supabase CLI 2.19.7
WARN: no SMS provider is enabled. Disabling phone login
2025/03/20 08:11:31 DNS Start: {Host:api.supabase.com}
2025/03/20 08:11:31 DNS Done: {Addrs:[{IP:104.22.2.252 Zone:} {IP:104.22.3.252 Zone:} {IP:172.67.23.199 Zone:}] Err:<nil> Coalesced:false}
2025/03/20 08:11:31 Connect Start: tcp 104.22.2.252:443
2025/03/20 08:11:31 Connect Done: tcp 104.22.2.252:443
2025/03/20 08:11:31 TLS Start
2025/03/20 08:11:31 TLS Done
...
2025/03/20 08:11:32 Recv First Byte
2025/03/20 08:11:32 Recv First Byte
2025/03/20 08:11:32 Recv First Byte
2025/03/20 08:11:32 Recv First Byte
2025/03/20 08:11:32 Recv First Byte
2025/03/20 08:11:32 Recv First Byte
Storage version not found.
2025/03/20 08:11:32 Recv First Byte
2025/03/20 08:11:32 Recv First Byte
Using connection pooler: postgresql://postgres.<PROJECT_ID>:[YOUR-PASSWORD]@aws-0-us-east-1.pooler.supabase.com:6543/postgres
Connecting to remote database...
2025/03/20 08:11:32 Connect Start: tcp 52.45.94.125:5432
2025/03/20 08:11:32 Connect Done: tcp 52.45.94.125:5432
2025/03/20 08:11:32 PG Send: {"Type":"StartupMessage","ProtocolVersion":196608,"Parameters":{"database":"postgres","user":"postgres.<PROJECT_ID>"}}
2025/03/20 08:11:42 Connect Start: tcp 44.216.29.125:5432
2025/03/20 08:11:42 Connect Done: tcp 44.216.29.125:5432
2025/03/20 08:11:42 PG Send: {"Type":"StartupMessage","ProtocolVersion":196608,"Parameters":{"database":"postgres","user":"postgres.<PROJECT_ID>"}}
2025/03/20 08:11:52 Connect Start: tcp 44.208.221.186:5432
2025/03/20 08:11:52 Connect Done: tcp 44.208.221.186:5432
2025/03/20 08:11:52 PG Send: {"Type":"StartupMessage","ProtocolVersion":196608,"Parameters":{"database":"postgres","user":"postgres.<PROJECT_ID>"}}
2025/03/20 08:12:02 Connect Start: tcp 52.45.94.125:5432
2025/03/20 08:12:02 Connect Done: tcp 52.45.94.125:5432
2025/03/20 08:12:02 PG Send: {"Type":"StartupMessage","ProtocolVersion":196608,"Parameters":{"database":"postgres","user":"postgres.<PROJECT_ID>"}}
2025/03/20 08:12:12 Connect Start: tcp 44.216.29.125:5432
2025/03/20 08:12:12 Connect Done: tcp 44.216.29.125:5432
2025/03/20 08:12:12 PG Send: {"Type":"StartupMessage","ProtocolVersion":196608,"Parameters":{"database":"postgres","user":"postgres.<PROJECT_ID>"}}
2025/03/20 08:12:22 Connect Start: tcp 44.208.221.186:5432
2025/03/20 08:12:22 Connect Done: tcp 44.208.221.186:5432
2025/03/20 08:12:22 PG Send: {"Type":"StartupMessage","ProtocolVersion":196608,"Parameters":{"database":"postgres","user":"postgres.<PROJECT_ID>"}}
failed to connect to postgres: failed to connect to `host=aws-0-us-east-1.pooler.supabase.com user=postgres.<PROJECT_ID> database=postgres`: failed to receive message (timeout: context deadline exceeded)
```

Going to try clearing the supabase action cache, but the latest run from 9h ago is connecting to an IPv6: `failed to connect to postgres: failed to connect to `host=db.***.supabase.co user=postgres database=postgres`: dial error (dial tcp [2600:1f18:2e13:9d0b:99e:8e65:804a:d031]:5432: connect: network is unreachable)`

**Comment by crro** [comment]
Checked my github actions and I'm not using any caches

**Comment by cpauwels** [comment]
Same here, exact same problem and not working in Github Actions on the 2 projects I have tried it on.

```
##[debug]Evaluating condition for step: 'Run supabase link --project-ref $PRODUCTION_PROJECT_ID'
##[debug]Evaluating: success()
##[debug]Evaluating success:
##[debug]=> true
##[debug]Result: true
##[debug]Starting: Run supabase link --project-ref $PRODUCTION_PROJECT_ID
##[debug]Loading inputs
##[debug]Loading env
Run supabase link --project-ref $PRODUCTION_PROJECT_ID
  supabase link --project-ref $PRODUCTION_PROJECT_ID
  supabase db push
  shell: /usr/bin/bash -e {0}
  env:
    SUPABASE_ACCESS_TOKEN: ***
    SUPABASE_DB_PASSWORD: ***
    PRODUCTION_PROJECT_ID: ***
    SUPABASE_INTERNAL_IMAGE_REGISTRY: ghcr.io
##[debug]/usr/bin/bash -e /home/runner/work/_temp/30e5[2](https://github.com/***/***/actions/runs/13972483305/job/39120006716#step:4:2)a7c-62e3-4018-94b9-311d72764f2d.sh
failed to connect to postgres: failed to connect to `host=db.***.supabase.co user=postgres database=postgres`: dial error (dial tcp [2a05:d014:1c06:5f0[3](https://github.com/***/***/actions/runs/13972483305/job/39120006716#step:4:3):405d:a08d:bf59:fbb1]:5432: connect: network is unreachable)
Try rerunning the command with --debug to troubleshoot the error.
Error: Process completed with exit code 1.
##[debug]Finishing: Run supabase link --project-ref $PRODUCTION_PROJECT_ID
```

**Comment by sweatybridge** [comment]
@crro the problem is the default cli version used by setup-cli action was [too old](https://github.com/supabase/setup-cli/issues/323), ie. 1.136.3. I've bumped it to the latest version to align with what we have. Could you give your CI another try?

Alternatively, you can set the action to always use the latest.

```
    - name: Install supabase
      uses: supabase/setup-cli@v1
      with:
        version: latest
```

**Comment by crro** [comment]
This issue has been fixed with that new version of my github action. Didn't have to add the `latest` piece, when the new version was available it picked up the new version!

My local issue had to do with my ISP not allowing IPv6. For anyone else that's curious, my local was failing this: https://test-ipv6.com/
