### ISSUE TITLE
ERROR: cannot drop function storage.get_level(text) because other objects depend on it (SQLSTATE 2BP01)

### ISSUE THREAD

**Issue by GrimLothar** [supabase/cli#3425]
# Bug report

- [X] I confirm this is a bug with Supabase, not with my own application. 
- [X] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

Trying to use supabase cli for the first time in an already existing project. After pulling the DB for the initial migration and starting supabase, I get the error in the title 
```
WARNING: You are running different service versions locally than your linked project:
supabase/storage-api:v1.19.3 => v1.22.2
Run supabase link to update them.
Seeding globals from roles.sql...
Applying migration 20250410152304_remote_schema.sql...
Applying migration 20250410153024_remote_schema.sql...
Stopping containers...
ERROR: cannot drop function storage.get_level(text) because other objects depend on it (SQLSTATE 2BP01)
At statement 32:                                                                                       
drop function if exists "storage"."get_level"(name text)  
Try rerunning the command with --debug to troubleshoot the error.
```

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Link existing project to cli `npx supabase link --project-ref [redacter]`
2. Pull db to get first migration file `npx supabase db  pull`
3. See this message as outcome `The auth and storage schemas are excluded. Run supabase db pull --schema auth,storage again to diff them.`
4. Run what was suggested `npx supabase db pull --schema auth,storage`
5. Try to start supabase `npx supabase start`

Get error

## Expected behavior

No errors should happen

## System information

- OS: macOS
- Browser N/A
- Version of supabase-js: 2.49.1
- Version of Node.js: v20.11.1

## Additional context

I found this person having the same problem: https://stackoverflow.com/questions/79512775/supabase-error-cannot-drop-function-storage-get-leveltext-because-other-objec

And with supposedly a workaround by initially running: 

`supabase db pull --schema public,auth,storage`

But like the comment on that answer states, after doing that, the auth and storage are still not pulled on the first pull, and you still get the initial warning `The auth and storage schemas are excluded`

**Comment by Hallidayo** [comment]
Hi all, I've moved this over to the cli repo.

**Comment by timotheduflos** [comment]
hello ! I've got the same issue too

**Comment by mwalterskirchen** [comment]
I found a temporary fix for this. You have to DROP CASCADE all the functions manually in the migration file like this:

```sql
drop function if exists "storage"."add_prefixes"(_bucket_id text, _name text) cascade;

drop function if exists "storage"."delete_prefix"(_bucket_id text, _name text) cascade;

drop function if exists "storage"."delete_prefix_hierarchy_trigger"() cascade;

drop function if exists "storage"."get_level"(name text) cascade;

drop function if exists "storage"."get_prefix"(name text) cascade;

drop function if exists "storage"."get_prefixes"(name text) cascade;

drop function if exists "storage"."objects_insert_prefix_trigger"() cascade;

drop function if exists "storage"."objects_update_prefix_trigger"() cascade;

drop function if exists "storage"."prefixes_insert_trigger"() cascade;

drop function if exists "storage"."search_legacy_v1"(prefix text, bucketname text, limits integer, levels integer, offsets integer, search text, sortcolumn text, sortorder text) cascade;

drop function if exists "storage"."search_v1_optimised"(prefix text, bucketname text, limits integer, levels integer, offsets integer, search text, sortcolumn text, sortorder text) cascade;

drop function if exists "storage"."search_v2"(prefix text, bucket_name text, limits integer, levels integer, start_after text) cascade;
```

as far as I understand it is caused by the functions depending on certain columns or triggers and that blocks the drop if you don't cascade it. This should be handled by the CLI though since doing this manually is not sustainable.

**Comment by sweatybridge** [comment]
Generally you don't want to be dropping functions from the storage schema.

The cause is most likely due to version mismatch between local and remote storage versions. You want to keep them in sync by linking your project before running db pull. For eg.

```
supabase link
supabase db pull --schema storage
``

**Comment by A-F-V** [comment]
> Generally you don't want to be dropping functions from the storage schema.
> 
> The cause is most likely due to version mismatch between local and remote storage versions. You want to keep them in sync by linking your project before running db pull. For eg.
> 
> ```
> supabase link
> supabase db pull --schema storage
> ```

Tried this and still getting the same error.

Only working solution so far is: https://github.com/supabase/cli/issues/3425#issuecomment-2805154132

**Comment by sweatybridge** [comment]
I managed to reproduce this. Will make a fix asap.

**Comment by damien-schneider** [comment]
The issue has been closed but it seems the error is still happening (using supabase `2.22.6`)

**Comment by sweatybridge** [comment]
This should have been fixed in v2.22.6. You will need to run `npx supabase@latest link` again as we've changed the way storage migration versions are synced.

**Comment by ritik99** [comment]
I'm on Supabase CLI v2.22.12 but I'm still facing this issue. Applying new migrations raises the error:

```
ERROR: cannot drop function storage.get_level(text) because other objects depend on it (SQLSTATE 2BP01)
At statement 30:                                                                                       
drop function if exists "storage"."get_level"(name text)                                               
Try rerunning the command with --debug to troubleshoot the error.
```
