### ISSUE TITLE
failed to connect to postgres

### ISSUE THREAD

**Issue by andim27** [supabase/cli#3960]
**Describe the bug**
Error connection to postgres after migration error

**To Reproduce**
1. Create migration files
2. supabase db push
 Ask:
Do you want to push these migrations to the remote database?
yes
Applying migration 20250730155824_my_data.sql...
Applying migration 20250731151101_next_data.sql...
ERROR: syntax error at or near "\" (SQLSTATE 42601)
At statement: 0                                    
\set ON_ERROR_STOP off                             
^  
Try rerunning the command with --debug to troubleshoot the error.
   
4. supabase db push
5. See error
Connecting to remote database...
failed to connect to postgres: failed to connect to `host=aws-0-eu-central-2.pooler.supabase.com user=cli_login_postgres.myId database=postgres`: AfterConnect error (ERROR: permission denied to set role "postgres" (SQLSTATE 42501))
Try rerunning the command with --debug to troubleshoot the error.

**System information**
Rerun the failing command with `--create-ticket` flag.
 - Ticket ID: [e.g. ab1ac733e31e4f928a4d7c8402543712]
 - Version of OS:mac os
 - Version of CLI: 2.33.7

**Comment by BrandontMitchell** [comment]
Same here, using latest tag for my actions

**Comment by sweatybridge** [comment]
Can you let me know your project id please? Or file a support ticket through https://supabase.green/dashboard/support/new

**Comment by RelevanceRo** [comment]
same problem. incredible. gg! 

Initialising cli_login_postgres role...
Forgot your password? Reset it from the Dashboard: https://supabase.com/dashboard/project/flzbapcmarphtlnjeqve/settings/database
Enter your database password: 
Connecting to remote database...
failed to connect to postgres: failed to connect to `host=aws-0-eu-north-1.pooler.supabase.com user=postgres.flzbapcmarphtlnjeqve database=postgres`: failed SASL auth (invalid SCRAM server-final-message received from server)
Try rerunning the command with --debug to troubleshoot the error.

**Comment by Shooteger** [comment]
Hello, I got the exact same problem as the Author here, same way.

**Comment by AlejandroMora15** [comment]
Same problem

**Comment by sweatybridge** [comment]
Could you share which postgres major version you are on? You can find it on the dashboard https://supabase.com/dashboard/project/_/settings/infrastructure

**Comment by yasunogithub** [comment]
same problem

**Comment by nyplex** [comment]
same problem

**Comment by johnnykoo84** [comment]
same issue. it hangs forever at

```
npx supabase link --project-ref myprojectref --debug
Initialising cli_login_postgres role...
2025/08/28 20:33:46 HTTP POST: https://api.supabase.com/v1/projects/<myprojectref>/database/query
```

**Comment by nyplex** [comment]
I had a similiar issue in the past and realised I had 2 tokens created with the same name. Both were created with the CLI for some reason. I've deleted one and it worked. You can check your tokens here https://supabase.com/dashboard/account/tokens. Hope this help.

**Comment by MitchSchwartz** [comment]
removing tokens did not work for me. same problem.

**Comment by appboypov** [comment]
same problem cant do anything with cli except select my project

**Comment by damarnez** [comment]
same issue, using the last version of the cli 2.39.2.

**Comment by sweatybridge** [comment]
This was affecting pg17 projects and should be fixed in v2.40.2. Could you give the beta release a try?

```bash
npx supabase@beta login
```

**Comment by MitchSchwartz** [comment]
Issue remains in beta.

`failed to connect to postgres: failed to connect to 'host=aws-1-eu-west-2.pooler.supabase.com user=cli_login_postgres.PROJECTID database=postgres': AfterConnect error (ERROR: permission denied to set role "postgres" (SQLSTATE 42501))`

**Comment by sweatybridge** [comment]
@MitchSchwartz could you send a support ticket so I can take a closer look at your project?

**Comment by MitchSchwartz** [comment]
@sweatybridge ticket submitted SU-244145

**Comment by ddbaron** [comment]
@sweatybridge same here, crash report: 6460db7f549c413a99071f5a86429f09
Ticket: SU-244270

**Comment by ddbaron** [comment]
Update: I switched from homebrew which is 'old' (and refuses to upgrade) at CLI 2.39.2 and am using npx instead (2.40.7) and it's working...

**Comment by alessandrolattao** [comment]
same here and both the latest and the beta version are not working

**Comment by thewengchan** [comment]
having the same issue here, nothing helps

**Comment by placelove** [comment]
I also keep having this issue.

**Comment by MitchSchwartz** [comment]
Dropping the CLI_LOGIN_POSTGRESS role and using supabase@latest solved the issue for me at long last.

**Comment by Mobe91** [comment]
I am also facing this issue.

Postgres version: 17.6.1.038
Supabase CLI version: 2.54.11

@MitchSchwartz How did you drop the CLI_LOGIN_POSTGRES role? I tried do it using `DROP ROLE cli_login_postgres;` via Supabase web query console, but I am getting a permission error.

**Comment by sweatybridge** [comment]
Dropping the role shouldn't matter. Could you try one of the workarounds here https://github.com/supabase/cli/issues/4302#issuecomment-3495112574

**Comment by MitchSchwartz** [comment]
> @MitchSchwartz How did you drop the CLI_LOGIN_POSTGRES role? I tried do it using `DROP ROLE cli_login_postgres;` via Supabase web query console, but I am getting a permission error.

Exactly like that unfortunately.

**Comment by mka-rainmaker** [comment]
Check Database - Settings - Network Bans
most probably you have your IP here (I had mine, no clue why), unban IP and everything will start to work

**Comment by Mobe91** [comment]
I've retried this after 5 hours and it randomly started to work without me changing anything.
Which makes sense judging from what this https://github.com/supabase/cli/issues/4302#issuecomment-3495112574 says.
> The reason is cli creates a temporary password for each login, but pooler maintains a password cache that becomes stale.

I suppose the password cache used by the pooler just expired.

**Comment by coldfire15** [comment]
> Check Database - Settings - Network Bans most probably you have your IP here (I had mine, no clue why), unban IP and everything will start to work

I had the same thing, I unbanned the IP and it's working, I still don't understand why (supabase ^2.58.5)
