### ISSUE TITLE
local - Bucket file upload in Supabase Dashboard fails silently

### ISSUE THREAD

**Issue by ganjiefong** [supabase/cli#4083]
**Describe the bug**
When uploading a file to a bucket from the Supabase Dashboard, the upload process appears to start (shows loading), then disappears without any success or error message. The file does not get uploaded.

**To Reproduce**
1. Open the Supabase Dashboard.
2. Navigate to Storage → select a bucket.
3. Click Upload and select a file.
4. Observe that the upload loading animation appears, then disappears without any success confirmation or error.
5. The file is not uploaded to the bucket.

**Expected behavior**
The file should upload successfully and appear in the bucket, or an error message should be displayed if the upload fails.

**System information**
- OS: Windows 11
- Browser: Firefox
- CLI Version: v2.39.2

**Comment by guomengtao** [comment]
I’m experiencing the same issue on Windows 11 with Firefox (Supabase CLI v2.39.2).  
When uploading a file via the Dashboard, the loading animation appears briefly and then disappears without any success confirmation or error message. The file never appears in the bucket.

Steps I tried:
1. Cleared browser cache and tried a different browser – same result.
2. Checked bucket permissions – they seem correct.
3. Tried smaller files – still fails silently.

It seems to be a dashboard-side bug. Could the team confirm if this is being addressed or suggest a workaround?

**Comment by tboot-0510** [comment]
I'm experiencing the same issue with the dashboard. 

However, it works if you upload the files using a script and call the supabase client. 
The files will appear in the dashboard

**Comment by neo-etremblay** [comment]
same issue here
EDIT : the issue for me was that I was using non-allowed characters in the file name, such as  "é". I removed it, and it started working right away.

**Comment by guomengtao** [comment]
Thanks so much for sharing this fix—it’s super helpful! I ran into the exact same silent failure issue earlier, and I never would’ve guessed special characters like "é" in filenames were the culprit. 

For anyone else stuck with this: double-check your filenames first! Ditching accented characters (é, à, ü, etc.), non-ASCII symbols, or even extra spaces and replacing them with plain letters, numbers, underscores, or hyphens seems to get the upload working right away. 

Such a simple tweak but a total lifesaver—really appreciate you circling back to post what worked for you!

**Comment by neo-etremblay** [comment]
@guomengtao My pleasure! Always happy to help :)

**Comment by Raflos10** [comment]
I'm getting this issue and I don't have any special characters. I can't even add a folder.

**Comment by ghost** [comment]
Same, i get the following error:

<img width="1603" height="37" alt="Image" src="https://github.com/user-attachments/assets/a1492144-670c-486c-9425-26acb4b0eae3" />

Here are my containers:

<img width="2677" height="293" alt="Image" src="https://github.com/user-attachments/assets/f88c3bc8-c93a-493b-ad98-8cb357af6d2a" />

**Comment by ganjiefong** [comment]
i still experiencing this issue at new cli version v2.45.5, here the docker error message:

`{"level":30,"time":"2025-09-24T05:05:19.500Z","pid":1,"hostname":"68efcb1b5779","region":"not-specified","reqId":"req-b","tenantId":"stub","project":"stub","reqId":"req-b","appVersion":"1.27.4","type":"request","req":{"region":"not-specified","traceId":"req-b","method":"POST","url":"/object/list/form_templates","headers":{"host":"supabase_storage_ies-system-supabase:5000","x_forwarded_proto":"http","x_forwarded_host":"supabase_kong_ies-system-supabase","x_forwarded_port":"54321","x_forwarded_prefix":"/storage/v1/","x_real_ip":"172.18.0.14","content_length":"89","content_type":"application/json","x_client_info":"supabase-js-node/2.49.3","accept":"*/*","user_agent":"node"},"hostname":"supabase_storage_ies-system-supabase:5000","remoteAddress":"172.18.0.5","remotePort":58512},"res":{"statusCode":200,"headers":{"content_type":"application/json; charset=utf-8","content_length":"2"}},"responseTime":5.40438200160861,"role":"service_role","resources":["/form_templates"],"operation":"storage.object.list","msg":"stub | POST | 200 | 172.18.0.5 | req-b | /object/list/form_templates | node"}`

**Comment by ganjiefong** [comment]
Since no one from the team has given a response, falling back to version 2.34.3 will fix the problem.

**Comment by sweatybridge** [comment]
I will share this issue with frontend team since it's only affecting uploads from the local dashboard.

**Comment by ArcConsultancy** [comment]
Has there been any update regarding this issue/bug?

I'm also experiencing this issue and would like to know if there has been a solution.

**Comment by Michota** [comment]
having same issue. 
as someone above stated, downgrading works, but it comes with few issues, so its not really a helpful thing, as we dont really want to use depereacted versions.

**Comment by ganjiefong** [comment]
This issue is fixed in the latest release v2.51.0, so I will close it.

**Comment by Syzygy2048** [comment]
> This issue is fixed in the latest release v2.51.0, so I will close it.

Still a problem in v2.72.7 at the very least. Can't drag and drop or upload via the upload button via the dashboard.

Was able to upload things via the supabase MCP though.

**Comment by rt-k3498** [comment]
I am also having the same issue
