### ISSUE TITLE
Supabase Migrations cannot handle `CREATE FUNCTION` with the `BEGIN ATOMIC` syntax

### ISSUE THREAD

**Issue by allezxandre** [supabase/cli#610]
# Bug report

## Describe the bug

It is not possible to create a procedure or function using the `BEGIN ATOMIC` syntax from PostgreSQL 14 in a Supabase migration.

Probably a side-effect, but running `supabase db diff` after such a function has been defined returns:

```sql
CREATE OR REPLACE FUNCTION public.add(
        a integer,
        b integer)
    RETURNS integer
    LANGUAGE 'sql'
    COST 100
    IMMUTABLE STRICT PARALLEL UNSAFE
AS $BODY$
$BODY$;
```

`supabase db diff --use-migra` does not have the issue:

```sql
CREATE OR REPLACE FUNCTION public.add(a integer, b integer)
 RETURNS integer
 LANGUAGE sql
 IMMUTABLE STRICT
BEGIN ATOMIC
 SELECT (a + b);
END
;
```

## To Reproduce

Create a new migration (`supabase migration new function-test`), and add to it the following sample `add` function:

```sql
CREATE FUNCTION add(a integer, b integer) RETURNS integer
LANGUAGE SQL
IMMUTABLE
RETURNS NULL ON NULL INPUT
BEGIN ATOMIC
    SELECT a + b;
END;
```

Running the migration fails with the following error:

```
Error: ERROR: syntax error at end of input (SQLSTATE 42601)
At statement 1:                                                          
                                                         
CREATE FUNCTION add(a integer, b integer) RETURNS integer
LANGUAGE SQL                                             
IMMUTABLE                                                
RETURNS NULL ON NULL INPUT                               
BEGIN ATOMIC                                             
    SELECT a + b;                                        
Try rerunning the command with --debug to troubleshoot the error.
```

## Expected behavior

The migration should complete.

## System information

- OS: all
- Version of supabase-js: 2.1.0
- Version of Node.js: 18 LTS

**Comment by allezxandre** [comment]
This might be related to `pgadmin`, but I see the issue has been solved upstream here: https://github.com/pgadmin-org/pgadmin4/issues/4785

**Comment by sweatybridge** [comment]
Thank you for reporting this issue. This is likely a problem with statement splitter https://github.com/supabase/cli/blob/main/internal/utils/parser/state.go not dealing with semicolons properly in begin atomic functions. 

We will look into it more in due course and address them.

**Comment by profiluefter** [comment]
Hi, I just encountered this issue with the `CREATE RULE` statement which also contains semicolons as part of the statement (but enclosed in parantesis).
I can verify using the debug flag that the statement is split incorrectly.

Technically, you can work around it by putting the statement inside a dynamic sql `EXECUTE` in a plpgsql `DO` block. This is however hilariously too complicated 😂

**Comment by rafonseca** [comment]
I guess the issue is exactly [here](https://github.com/supabase/cli/blob/92137b907645ebfb645e5c82e1049531b1735304/internal/utils/parser/token.go#L117), in SplitAndTrim function.

The workaround using dynamic SQL is a big no for me. Any progress here?

Thanks in advance

**Comment by sweatybridge** [comment]
Thanks for bumping this issue. I've pushed my changes to a draft PR. Will circle back again early next week.

**Comment by martinsellergren** [comment]
Still seeing issues with begin atomic. I think related to case expressions, perhaps due to the 'end' statement of case expressions.

Failing:
```dart
create
or replace function public."queryPublishedStories" ("queryOrder" jsonb) returns setof "apiStory" language sql
begin atomic
select
    *
from
    "apiStory" s
order by
    case "queryOrder" ->> 'runtimeType'
        when 'DatePublished' then s."datePublished"
    end;

end;
```
