### ISSUE TITLE
`db push`: Permission error with cron extension

### ISSUE THREAD

**Issue by henningko** [supabase/cli#647]
# Bug report

## Describe the bug

I am trying to to move my production environment into a CI/CD workflow as outlined here: https://supabase.com/docs/guides/cli/managing-environments

When GitHub processes the first push to an empty staging, it fails with the following error:
`ERROR: must be owner of table job (SQLSTATE 42501);`

A previous permission issue, similar to [this discussion ](https://github.com/supabase/supabase/discussions/6326) and #128, I fixed by altering ownership from `supabase_admin` to `postgres` in the initial `…remote_commit.sql`.

However, there seems to be an issue with the ownership of the table `cron.job`, which is not explicitly created in the `…remote_commit.sql` but by creating `pg_cron`.

 <details><summary>Running this with `—debug` yields no additional info:</summary>

```
2022/11/28 19:51:48 PG Recv: {"Type":"ErrorResponse","Severity":"ERROR","SeverityUnlocalized":"ERROR","Code":"42501","Message":"must be owner of table job","Detail":"","Hint":"","Position":0,"InternalPosition":0,"InternalQuery":"","Where":"","SchemaName":"","TableName":"","ColumnName":"","DataTypeName":"","ConstraintName":"","File":"aclchk.c","Line":3583,"Routine":"aclcheck_error","UnknownFields":null}
```
</details>

## To Reproduce
Use the following migration
https://gist.github.com/henningko/f133e260881fbb998e0280761a7668cd

and use `db push` linked to an empty/new supabase project.

## Expected behavior

When creating an initial migration, this should work on a new supabase project without errors.

## System information

Default GitHub runner/actions as published here:
https://supabase.com/docs/guides/cli/managing-environments

**Comment by henningko** [comment]
I just ran

```sql
CREATE EXTENSION IF NOT EXISTS "pg_cron" WITH SCHEMA "extensions”;
```

when signed in as user `postgres`. The result of  `select tablename, tableowner from pg_tables WHERE tablename = 'job’;`:
| tablename | tableowner     |
|-----------|----------------|
| job       | supabase_admin |


So the quick fix seems to be to change owners of the `cron` tables back to `supabase_admin`. However, root cause of the migration problems seem to be that it’s not clear when `supabase_admin` is used, and when `postgres` is used.

**Comment by soedirgo** [comment]
Hey there, thanks for reporting this issue.

> The result of select tablename, tableowner from pg_tables WHERE tablename = 'job’;

One thing to note is on the hosted environment, extension creation is delegated to a superuser, which is why the owner becomes `supabase_admin` instead of `postgres`.

> supabase_admin is the only superuser on hosted environment, while postgres is a superuser on local AND the user through which migrations are run

Yes, this does get problematic - eventually we want to make the local environment as close as possible to the hosted environment so this kind of problem doesn't arise.

> set postgres on remote machines to a superuser via ALTER ROLE postgres SUPERUSER

This wouldn't work in the near future since we will be [changing the dashboard role to a non-superuser](https://github.com/supabase/supabase/discussions/9314).

I wonder if simply commenting out the offending lines the migration would help here (i.e. `ALTER TABLE "cron"...`, `GRANT ... ON "cron"...`, etc.) - they live on a separate schema `"cron"`, and by default, roles which are subject to RLS like `anon` and `authenticated` wouldn't have access to things in that schema.

**Comment by henningko** [comment]
Yeah, seems like those statements are unnecessary—at the same time, for anything that's done via the dashboard UI pre-migration, it’s hard for the person doing the migration to judge what statements are not required. Think just sorting out the local vs hosted environments and users will take care of a lot of these issues.

**Comment by henningko** [comment]
Building migrations/diffs via `supabase db diff new_feature -f new_features` also fails with errors unless all cron-related commands from the initial commit are removed/commented:
```
supabase db diff locations -f locations --debug
Error: Error starting shadow database: ERROR:  can only create extension in database postgres
DETAIL:  Jobs must be scheduled from the database configured in cron.database_name, since the pg_cron background worker reads job descriptions from this database.
HINT:  Add cron.database_name = 'supabase_shadow' in postgresql.conf to use the current database.
```

**Comment by sweatybridge** [comment]
> Building migrations/diffs via supabase db diff new_feature -f new_features also fails

We have fixed a few issues with `db diff` in the latest CLI. The `cron` schema is no longer dumped by default as it's managed by the extension. Please give it a try to see if it solves your issue.

**Comment by alexeigs** [comment]
@sweatybridge @soedirgo Does this mean, as of today, extension-related stuff still can't be fully mirrored and handled through migrations with the local development environment (but have to be documented "manually")?

**Comment by sweatybridge** [comment]
All extensions can be enabled through migration file now. @alexeigs are you running into any specific issues?

**Comment by William-LP** [comment]
@sweatybridge I've just tried enabling and setting up a cron_job using a migration file but I run into privileges issues.

`Error: ERROR: 42501: must be owner of table job `

I cannot add jobs, neither update the RLS using the `supabase db reset | push` commands.

Am I missing anything ?
