### ISSUE TITLE
Auth.signUp Error in Local Env with Supabase CLI

### ISSUE THREAD

**Issue by alteredorange** [supabase/cli#9]
# Bug report

## Describe the bug
supabase.auth.signup on local setup gives 'Database error finding user'.

Installed supabase cli, set up a local project, and then tried to do a simple user signup. On signup I get a status: 500 with message: Database error finding user.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. supabase init
2. localhost:8000
3. postgres port 5477 (only thing different from default)
4. create index.js with the following:
```
import { createClient } from '@supabase/supabase-js'
const SUPABASE_URL = 'http://localhost:8000'
const SUPABASE_ANON_KEY = 'key-here'
const supabase = createClient(SUPABASE_URL, SUPABASE_ANON_KEY)

const main = async () => {
  const { user, session, error } = await supabase.auth.signUp({
    email: 'hi@gmail.com',
    password: 'superpasswordtighty',
  })
  console.log(user)       //null
  console.log(session)  //null
  console.log(error)     //{ message: 'Database error finding user', status: 500 }
}
main()
```

## Expected behavior

A user would be created in the database.  I can connect to postgres just fine, and it looks like everything is there (as far as I know).  I also tried the auth.signIn method, and I get the same error (which makes sense since there's no user yet). Not sure if the signUp method is getting it's wires crossed with singIn?

## Screenshots
postgres database:
![image](https://user-images.githubusercontent.com/2141012/113212397-eea96b80-9233-11eb-9287-c9431468ec36.png)

## System information

- OS: Windows running Ubuntu and Docker Desktop through WSL2

- Version of supabase-js: 1.7.6, cli: 0.3.3
- Version of Node.js: 15.6.0

**Comment by KrisCoulson** [comment]
I raises a similar issue here. https://github.com/supabase/supabase/discussions/1023

Although I am not sure I have the auth.users table in my local db.

**Comment by kiwicopple** [comment]
@soedirgo Looks like it's here:

https://github.com/supabase/cli/blob/5666b4dad71da0d0d96de040952bfc4d0804a669/src/templates/init/docker/docker-compose.yml#L29

If the port is something other than `5432` I guess GoTrue can't connect

**Comment by KrisCoulson** [comment]
@kiwicopple just following up here. I did run init on port 5432, so it is a little different. But when running `supabase start` it doesn't seem any of the supabase tables were created in the database.

**Comment by kiwicopple** [comment]
Thanks for the follow up @KrisCoulson - let us investigate 👍

**Comment by awalias** [comment]
there should be some more specific error messages from the gotrue logs in docker, it is almost definitely the case that gotrue either:

- cannot connect to the database
- cannot see or access the auth.users table
- some trigger is causing the insert transaction to fail (seen this a couple of times in the wild)

@KrisCoulson can you try [checking](https://docs.docker.com/engine/reference/commandline/logs/) or tailing the gotrue logs

**Comment by soedirgo** [comment]
These are the logs for me:

```
time="2021-04-01T08:45:39.729628Z" level=debug msg="Set log level to: debug"
time="2021-04-01T08:45:39Z" level=info msg="GoTrue API started on: 0.0.0.0:9999"
time="2021-04-01T08:46:35Z" level=info msg="request started" component=api method=POST path=/signup referer="http://localhost:3000/" remote_addr="172.31.0.2:51926" request_id=90b5f6be-2d6e-40f1-a774-700e1e538b01
time="2021-04-01T08:46:35Z" level=error msg="500: Database error finding user" component=api error="error finding user: ERROR: relation \"users\" does not exist (SQLSTATE 42P01)" method=POST path=/signup referer="http://localhost:3000/" remote_addr="172.31.0.2:51926" request_id=90b5f6be-2d6e-40f1-a774-700e1e538b01
time="2021-04-01T08:46:35Z" level=info msg="request completed" component=api duration=68992000 method=POST path=/signup referer="http://localhost:3000/" remote_addr="172.31.0.2:51926" request_id=90b5f6be-2d6e-40f1-a774-700e1e538b01 status=500
```

Maybe relevant: `auth` isn't in `search_path`, but `auth.users` exists

**Comment by awalias** [comment]
I can also replicate - debugging now

**Comment by alteredorange** [comment]
Tried a few more times with different settings, still had the same problem. I deleted `.supabase` and tried again with port: 5432. Interestingly enough, `supabase init` gives me the exact same credentials each time. Still got the same error, so created an entirely new directory, deleted the docker group, and tried `supabase init` again with the defaults.  Still got the same credentials, and the same `Database error finding user`.

**Comment by soedirgo** [comment]
@alteredorange this should be fixed in #12 (you'll have to remove `.supabase` and re-`init`). I'll just merge it in now - let me know if it works!

**Comment by alteredorange** [comment]
Yes, I can sign in now, thanks for getting that sorted!!

**Comment by KrisCoulson** [comment]
@soedirgo I pulled the latest and re-init and I still don't seem to have `auth.users` generated in my postgres db. Maybe I am setting it up wrong

**Comment by alteredorange** [comment]
@KrisCoulson did you delete your docker containers as well? Didn't work for me until I also deleted all supabase docker containers, and then `supabases start` rebuilt them the correct way.

**Comment by KrisCoulson** [comment]
@alteredorange Yeah I killed the containers and re-init and still no luck my database is completely empty

**Comment by kiwicopple** [comment]
@KrisCoulson can I please doublecheck that you *removed* the containers, not just killed them?

Here's a few useful docker commands (note that *all* is everything on your machine, not just supabase)

```
# List all containers
docker ps -a -q

# Stop all containers
docker stop $(docker ps -a -q)

# Kill all containers
docker kill $(docker ps -q)

# Remove all containers
docker rm $(docker ps -a -q)

# Remove all docker images
docker rmi $(docker images -q)

# Prune all volumes
docker system prune -a -f --volumes
```

**Comment by soedirgo** [comment]
When you check the `supabase-db` container logs, does it have a line that says `ALTER ROLE` in it? If not, looks like it wasn't building the image properly.

**Comment by KrisCoulson** [comment]
@kiwicopple this time just to make sure everything was clear I removed all containers and images.

@soedirgo a screen recording of the container logs. It does have `ALTER ROLE`

https://user-images.githubusercontent.com/6943688/113379287-ef262d00-932d-11eb-99f0-f0ec2cd7180d.mov

**Comment by soedirgo** [comment]
Yes, that looks right. The `auth` schema doesn't show up in my Postgres IDE, but when I run `select * from auth.users;` from psql it can find the table.

**Comment by KrisCoulson** [comment]
@soedirgo I have been using tablePlus and if I connect a supabase a hosted supabase db the schema's show fine. The local one does not show the schemas. But even so selecting from the auth.users does not find the table.


https://user-images.githubusercontent.com/6943688/113423785-efe9ae00-9383-11eb-817b-e334840aaae9.mov

**Comment by soedirgo** [comment]
Hmm... this bug keeps eluding me. 😅

Maybe a last straw: can you try opening a shell to the container and run the query with psql directly in it? Failing that, if you run `tail -f /var/lib/postgresql/data/log/postgresql.csv` inside the container, and *then* run the query from anywhere, the errors should pop up there.

**Comment by KrisCoulson** [comment]
@soedirgo looks like auth table exists when directly inside of the container. Also ran `tail -f` 

![image](https://user-images.githubusercontent.com/6943688/113435981-b7a09a80-9398-11eb-95dd-b103beabc9ae.png)

**Comment by soedirgo** [comment]
OK, that's good. My guess is psql was run on the wrong port. Can you check if the `supabase-db` container is running on 5432 on the host? i.e. you should see this:

<img width="401" alt="Screenshot 2021-04-03 at 12 57 00 AM" src="https://user-images.githubusercontent.com/31685197/113436622-a21e8580-9417-11eb-9b78-f3286b46ded9.png">

And when you have any errors from psql, it should show up in the tail logs above.

**Comment by KrisCoulson** [comment]
![image](https://user-images.githubusercontent.com/6943688/113437991-888c2800-939c-11eb-877d-c1aca6576055.png)

This is what mine looks like

**Comment by soedirgo** [comment]
You shouldn't have to set up the db, it's self contained. I tried running a Postgres server while the `supabase-db` container was up - turns out it intercepts connections to 5432, so when I psql'd I connected to the native local server rather than the container. Stopping the Postgres server should fix this.

**Comment by KrisCoulson** [comment]
@soedirgo that was it!
I ended up having to run `brew services stop postgresql` Might be worth mention that in the documentation this edge case where local connections highjack the connection to the docker contiainer.

Thanks for your help!

**Comment by soedirgo** [comment]
Whew! Glad to have this resolved. 😄

**Comment by KrisCoulson** [comment]
@soedirgo I guess one more question is the best way to have access to local dbs just to update the port when running a local postgres?

My app also uses a test_db for storing temporary test data. So to have them running I would need to start postgres server on a seperate port and have the docker-container use port 5432

@kiwicopple mentioned that GoTrue cant connect unless it is on 5432
> If the port is something other than 5432 I guess GoTrue can't connect

**Comment by soedirgo** [comment]
> If the port is something other than 5432 I guess GoTrue can't connect

I don't think this applies, 5432 is the default host port, but the container port is always 5432, so no problem there.

Your best bet is probably to reinit, though there are [probably ways to do this](https://stackoverflow.com/questions/19335444/how-do-i-assign-a-port-mapping-to-an-existing-docker-container) if you really have to.
